// dva-umi/src/components/DashboardItem.jsx
import React,{Component} from "react";
import {connect} from 'dva';
import Link from 'umi/link';

@connect()
export default class DashboardItem extends Component {
  render(){
    let {id,name} = this.props;
    return(
      <Link className="cnt-c1 col-1-4" to={`/details/${id}?name=${name}`}>
        <div className="cnt-c1 module hero">
          <h4 className="cnt-c1">{name}</h4>
        </div>
      </Link>
    )
  }
}

// vue/src/components/DashboardItem.vue
<template>
    <router-link class="cnt-c1 col-1-4" :to="{path:'./details/'+id}">
        <div class="cnt-c1 module hero">
            <h4 class="cnt-c1">{{ name }}</h4>
        </div>
    </router-link>
</template>

<script lang="ts">
    import Vue from 'vue';
    import {Component,Prop} from 'vue-property-decorator';

    @Component
    export default class DashboardItem extends Vue {
        @Prop() private name:string;
        @Prop() private id:number;
    }
</script>
