// vue/src/components/HeroItem.vue
<template>
    <li @click="select" class="cnt-c3">
        <span class="cnt-c3 badge">{{ id }}</span>
        <span class="cnt-c3">{{ name }}</span>
        <button @mousedown="del" class="cnt-c3 delete">x</button>
    </li>
</template>

<script lang="ts">
    import Vue from 'vue';
    import {Component, Prop} from 'vue-property-decorator';
    import {Action} from 'vuex-class';

    @Component({
        data:()=>({isSelected:false})
    })
    export default class HeroItem extends Vue {
        @Prop() private id:number;
        @Prop() private name:string;
        private isSelected: boolean;

        @Action('delHero') private delHero;

        del(){
            console.log('id',this.id,'name',this.name);
            this.delHero(this.id);
            if(this.isSelected){
                this.$emit('select',0);
            }
        }
        select(){
            this.isSelected = true;
            this.$emit('select',this.id);
        }
    }
</script>

// dva-umi/src/components/HeroItem.jsx
import React,{Component} from "react";
import {connect} from 'dva';
import {cAction} from "../utils/ReduxUtil";

@connect(null,{
  select:(id) => cAction('hero/selectedHero',id),
  del:(id) => cAction('hero/delEff',id)
})
export default class HeroItem extends Component {

  selectHero = () => {
    let {select,id} = this.props;
    select(id);
  };

  delHero = (e) => {
    let {del,id} = this.props;
    del(id);
    e.stopPropagation();
  };

  render(){
    let {id,name,isSelected} = this.props;
    return(
      <li onClick={this.selectHero} className={`cnt-c3 ${isSelected ? 'selected' : ''}`}>
        <span className="cnt-c3 badge">{id}</span>
        <span className="cnt-c3">{name}</span>
        <button onClick={this.delHero} className="cnt-c3 delete">x</button>
      </li>
    )
  }
}
